### ISSUE TITLE
updateEdgeWithKey type doesn't match documentation

### ISSUE THREAD

**Issue by markjlorenz** [graphology/graphology-types#13]
This may be a reading issue on my part, because I'm not that familiar with Typescript, but I believe the type definition for `updateEdgeWithKey` is out of sync with the documentation:

[Documentation](https://github.com/graphology/documentation/blob/407fa800c28ddf81f87dca0682382b11efa035e2/docs/mutation.md#updateedgewithkey)
```
graph.updateEdgeWithKey('J->M', 'John', 'Martha', attr => {
```
(4 parameters)

[Type definition](https://github.com/graphology/graphology-types/blob/8b487bf366c56722de1ea1cdd743d19da0fde180/index.d.ts#L461-L465)
```
  updateEdgeWithKey(
    source: NodeKey,
    target: NodeKey,
    updater?: (attributes: EdgeAttributes) => EdgeAttributes
  ): string;
```
(3 parameters)

**Comment by Yomguithereal** [comment]
You are right, there is an issue with the type definition of the function indeed. Let me fix that.

**Comment by markjlorenz** [comment]
Thank you!  v2.0.0 is great by the way.  Thank you for contributing this library ❤️

**Comment by Yomguithereal** [comment]
v0.19.4 is live with a fix

**Comment by Yomguithereal** [comment]
oh no sorry, I need an additional bump

**Comment by Yomguithereal** [comment]
now v0.19.5 is live with a fix
