### ISSUE TITLE
Should we switch to peer deps when relying on graphology-types

### ISSUE THREAD

**Issue by Yomguithereal** [graphology/graphology-types#8]
We already had our first compatibility issues. Maybe it should be a peer dependency of libraries so that the user needs to install a unique version.

**Comment by Yomguithereal** [comment]
@zakjan do you have an opinion about this? Do you know how TS ecosystem usually handle this?

**Comment by zakjan** [comment]
Hmm, weird, could you forward here the bug report? I thought we covered all potential issues with default types.

Besides that, yes, if a library depends on another library, and doesn't want to bundle a specific version, I'd try peerDependencies, same as in JS.

**Comment by Yomguithereal** [comment]
Hello @zakjan. You can stumble upon the problem, typically, if you install graphology v0.18.0 alongside graphology-metrics which currently relies on an older graphology-types version. This will install two different graphology-types in the dep tree which will confuse, rightly so, TypeScript. I agree that in JS the solution to this particular problem would be to switch to peer deps, with all the inconvenients it can also have. I was just wondering whether TS had another solution to this kind of problem.
